"""teste com endereco em salao

Revision ID: 00da7e1c92e3
Revises: 6f5b32972dfc
Create Date: 2024-05-19 18:56:29.652762

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '00da7e1c92e3'
down_revision: Union[str, None] = '6f5b32972dfc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
