"""teste com endereco em salao 2

Revision ID: 3dbefbc34ee2
Revises: 00da7e1c92e3
Create Date: 2024-05-19 18:57:28.185472

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3dbefbc34ee2'
down_revision: Union[str, None] = '00da7e1c92e3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('salao', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'endereco', ['endereco_id'], ['id'])

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('salao', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    # ### end Alembic commands ###
