"""Ajuste nos models

Revision ID: 517c613b1a96
Revises: df3ebcd0589d
Create Date: 2024-05-18 02:32:44.548983

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '517c613b1a96'
down_revision: Union[str, None] = 'df3ebcd0589d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contato',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('telefone', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('instagram', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_contato_id'), 'contato', ['id'], unique=False)
    op.create_table('endereco',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('rua', sa.String(), nullable=True),
    sa.Column('numero', sa.String(), nullable=True),
    sa.Column('bairro', sa.String(), nullable=True),
    sa.Column('cep', sa.String(), nullable=True),
    sa.Column('cidade', sa.String(), nullable=True),
    sa.Column('estado', sa.String(), nullable=True),
    sa.Column('complemento', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_endereco_id'), 'endereco', ['id'], unique=False)
    op.create_table('salao',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(), nullable=True),
    sa.Column('porcentagemComissao', sa.Float(), nullable=True),
    sa.Column('endereco_id', sa.Integer(), nullable=True),
    sa.Column('contato_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['contato_id'], ['contato.id'], name='fk_salao_contato'),
    sa.ForeignKeyConstraint(['endereco_id'], ['endereco.id'], name='fk_salao_endereco'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_salao_id'), 'salao', ['id'], unique=False)
    op.create_table('pessoa',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(), nullable=True),
    sa.Column('dataNascimento', sa.DateTime(), nullable=True),
    sa.Column('salao_id', sa.Integer(), nullable=True),
    sa.Column('contato_id', sa.Integer(), nullable=True),
    sa.Column('endereco_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['contato_id'], ['contato.id'], name='fk_pessoa_contato'),
    sa.ForeignKeyConstraint(['endereco_id'], ['endereco.id'], name='fk_pessoa_endereco'),
    sa.ForeignKeyConstraint(['salao_id'], ['salao.id'], name='fk_pessoa_salao'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pessoa_id'), 'pessoa', ['id'], unique=False)
    op.create_table('servico',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(), nullable=True),
    sa.Column('descricao', sa.String(), nullable=True),
    sa.Column('valorAPartir', sa.Float(), nullable=True),
    sa.Column('duracao', sa.Integer(), nullable=True),
    sa.Column('salao_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['salao_id'], ['salao.id'], name='fk_servico_salao'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_servico_id'), 'servico', ['id'], unique=False)
    op.create_table('cliente',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pessoa_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['pessoa_id'], ['pessoa.id'], name='fk_cliente_pessoa'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cliente_id'), 'cliente', ['id'], unique=False)
    op.create_table('funcionario',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('senha', sa.String(), nullable=True),
    sa.Column('admin', sa.Boolean(), nullable=True),
    sa.Column('porcentagemComissao', sa.Float(), nullable=True),
    sa.Column('pessoa_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['pessoa_id'], ['pessoa.id'], name='fk_funcionario_pessoa'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_funcionario_id'), 'funcionario', ['id'], unique=False)
    op.create_table('comanda',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('data', sa.DateTime(), nullable=True),
    sa.Column('statusPagamento', sa.String(), nullable=True),
    sa.Column('valorTotal', sa.Float(), nullable=True),
    sa.Column('cliente_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['cliente_id'], ['cliente.id'], name='fk_comanda_cliente'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_comanda_id'), 'comanda', ['id'], unique=False)
    op.create_table('atividade',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('preco', sa.Float(), nullable=True),
    sa.Column('comanda_id', sa.Integer(), nullable=True),
    sa.Column('funcionario_id', sa.Integer(), nullable=True),
    sa.Column('servico_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['comanda_id'], ['comanda.id'], name='fk_atividade_comanda'),
    sa.ForeignKeyConstraint(['funcionario_id'], ['funcionario.id'], name='fk_atividade_funcionario'),
    sa.ForeignKeyConstraint(['servico_id'], ['servico.id'], name='fk_atividade_servico'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_atividade_id'), 'atividade', ['id'], unique=False)
    op.create_table('pagamento',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('data', sa.DateTime(), nullable=True),
    sa.Column('valor', sa.Float(), nullable=True),
    sa.Column('forma', sa.String(), nullable=True),
    sa.Column('comanda_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['comanda_id'], ['comanda.id'], name='fk_pagamento_comanda'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pagamento_id'), 'pagamento', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_pagamento_id'), table_name='pagamento')
    op.drop_table('pagamento')
    op.drop_index(op.f('ix_atividade_id'), table_name='atividade')
    op.drop_table('atividade')
    op.drop_index(op.f('ix_comanda_id'), table_name='comanda')
    op.drop_table('comanda')
    op.drop_index(op.f('ix_funcionario_id'), table_name='funcionario')
    op.drop_table('funcionario')
    op.drop_index(op.f('ix_cliente_id'), table_name='cliente')
    op.drop_table('cliente')
    op.drop_index(op.f('ix_servico_id'), table_name='servico')
    op.drop_table('servico')
    op.drop_index(op.f('ix_pessoa_id'), table_name='pessoa')
    op.drop_table('pessoa')
    op.drop_index(op.f('ix_salao_id'), table_name='salao')
    op.drop_table('salao')
    op.drop_index(op.f('ix_endereco_id'), table_name='endereco')
    op.drop_table('endereco')
    op.drop_index(op.f('ix_contato_id'), table_name='contato')
    op.drop_table('contato')
    # ### end Alembic commands ###
