"""Mudanca nas chaves de funcionario e cliente

Revision ID: 5a25b153f894
Revises: 517c613b1a96
Create Date: 2024-05-18 04:07:36.827179

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5a25b153f894'
down_revision: Union[str, None] = '517c613b1a96'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cliente', sa.Column('salao_id', sa.Integer(), nullable=True))
    op.create_foreign_key('fk_cliente_salao', 'cliente', 'salao', ['salao_id'], ['id'])
    op.add_column('funcionario', sa.Column('salao_id', sa.Integer(), nullable=True))
    op.create_foreign_key('fk_funcionario_salao', 'funcionario', 'salao', ['salao_id'], ['id'])
    op.drop_constraint('fk_pessoa_salao', 'pessoa', type_='foreignkey')
    op.drop_column('pessoa', 'salao_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pessoa', sa.Column('salao_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('fk_pessoa_salao', 'pessoa', 'salao', ['salao_id'], ['id'])
    op.drop_constraint('fk_funcionario_salao', 'funcionario', type_='foreignkey')
    op.drop_column('funcionario', 'salao_id')
    op.drop_constraint('fk_cliente_salao', 'cliente', type_='foreignkey')
    op.drop_column('cliente', 'salao_id')
    # ### end Alembic commands ###
