"""Coluna de data de fechamento

Revision ID: 7fab04f751d8
Revises: c4e44e56c913
Create Date: 2024-05-25 22:06:51.179085

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7fab04f751d8'
down_revision: Union[str, None] = 'c4e44e56c913'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comanda', schema=None) as batch_op:
        batch_op.add_column(sa.Column('dataFechamento', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comanda', schema=None) as batch_op:
        batch_op.drop_column('dataFechamento')

    # ### end Alembic commands ###
