"""teste com endereco em funcionario

Revision ID: c4e44e56c913
Revises: 804bfa230749
Create Date: 2024-05-19 20:40:52.098887

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c4e44e56c913'
down_revision: Union[str, None] = '804bfa230749'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('funcionario', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'endereco', ['endereco_id'], ['id'])

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('funcionario', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    # ### end Alembic commands ###
