"""Conserto na tabela pagamento e comanda

Revision ID: c9b33094b955
Revises: ec75691e99a7
Create Date: 2024-05-19 13:23:34.476809

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c9b33094b955'
down_revision: Union[str, None] = 'ec75691e99a7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
