"""Tabela salarios 3

Revision ID: d09db64b4bd9
Revises: c6aff8183fd4
Create Date: 2024-05-27 00:06:39.252188

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd09db64b4bd9'
down_revision: Union[str, None] = 'c6aff8183fd4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('salario',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('valor', sa.Float(), nullable=True),
    sa.Column('qntAtividades', sa.Integer(), nullable=True),
    sa.Column('qntDiasTrabalhados', sa.Integer(), nullable=True),
    sa.Column('dataInicio', sa.DateTime(), nullable=True),
    sa.Column('dataFim', sa.DateTime(), nullable=True),
    sa.Column('funcionario_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['funcionario_id'], ['funcionario.id'], name='fk_salario_funcionario'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('salario', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_salario_id'), ['id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('salario', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_salario_id'))

    op.drop_table('salario')
    # ### end Alembic commands ###
